### ISSUE TITLE
Why not sio2 ?

### ISSUE THREAD

**Issue by Wolf480pl** [algochecker/algochecker-engine#1]
What's wrong with [sio2][1] that you want to make another checker from scratch?

[1]:https://github.com/sio2project

**Comment by icedevml** [comment]
Hello,

is it possible to test problems like "write a strategy for playing chess" with SIO2? Algochecker supports various non-typical testing scenarios like: two programs with stdin/out piped together with `mkfifo` - first program is written by the author of the problem and the second one goes from the user. They are communicating with some protocol and at the end of the test, the first program is evaluating if the test went succesfully and tells the amount of points to be assigned.

There is also another advantage - it's Docker based, so you can get almost any environment you need in a quite fast way (e.g. enabling support of Ruby or Golang for the source code is like 2 or 3 hours of work for a developer).

What we are doing is basically experimenting if we are able to make a friendly and extensible platform. Not necessarily competing with any other apps like that.

**Comment by Wolf480pl** [comment]
Interesting.

The use of Docker for evaluation environments seems like a good idea.
The two-way communication between the evaluated program and a checking program also seems like a nice feature.

I think you should make your readme/website express these differences, because on the first glance it looks like "just another algorithmic task checker because everyone rolls their own because NIH syndrome".

**Comment by icedevml** [comment]
There is a web page of our project: https://algochecker.com/

We don't have too much written in there yet, but if you are interested, there is a VirtualBox image of already-configured Ubuntu Desktop with Algochecker set-up for demonstrative purposes. You can download it and play with two exemplary testing scenarios (basic file-based testing and simple problem with piped programs).

We are working on the documentation, stability and ease of deployment. Soon we will share something.

Thanks for your input.

**Comment by Michcioperz** [comment]
I'll drop my thoughts here, since it's not really worth a new issue:

Have you considered distributing the demo via a Vagrantfile? I suppose it's not nearly as instant as a VirtualBox image, but it would allow tinkerers to get a quick grasp of the setup while also enabling people with poorer network connections to try the thing out faster.

**Comment by icedevml** [comment]
Of course the VirtualBox solution is rather a temporary one, it's very probable that such Vagrantfile or some other similiar solution will appear within one or two weeks.

**Comment by marmistrz** [comment]
Btw. we have our IRC channel, #sio2project at Freenode.net :)
